name: Run Go File

on:
  workflow_call:
    inputs:
      go-file-repo:
        type: 'string'
        default: 'workflow-sync-poc/common'
        description: 'The repository with the Go file. By default "workflow-sync-poc/common".'
      go-version:
        type: 'string'
        default: 'stable'
        description: 'The version of Go to use (e.g. "1.22.5"). By default "stable".'
      go-file-path:
        type: 'string'
        required: true
        description: 'The file path to the Go file (e.g. "code/code-1.go").'
      go-args:
        type: 'string'
        default: ''
        description: 'A space-separated list of string arguments passed to the Go file (e.g. "component-1").'

jobs:
  run-go-file:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ("${{ inputs.go-file-repo }}")
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.go-file-repo }}
          path: 'repository'

      - name: Setup Go ("${{ inputs.go-version }}")
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run Go File ("${{ inputs.go-file-path }}")
        env:
          GO_FILE_REPO: "${{ inputs.go-file-repo }}"
          GH_WORKFLOW_RUN_ID: "${{ github.run_id }}"
          GH_PAT_MF: "${{ secrets.GH_PAT_MF }}"
          GH_PAT_AYYXD: "${{ secrets.GH_PAT_AYYXD }}"
        run: |
          cd repository  # Necessary so that the go.mod file can be found.
          go run ${{ inputs.go-file-path }} ${{ inputs.go-args }}