name: Run Go File

on:
  workflow_call:
    inputs:
      go-file-repo:
        type: 'string'
        default: 'MaxFogwall/common'
        description: 'The repository with the Go file. By default "MaxFogwall/common".'
      go-version:
        type: 'string'
        default: 'stable'
        description: 'The version of Go to use (e.g. "1.22.5"). By default "stable".'
      go-file-path:
        type: 'string'
        required: true
        description: 'The file path to the Go file (e.g. "code/code-1.go").'

jobs:
  run-go-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ("${{ inputs.go-file-repo }}")
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.go-file-repo }}
          path: 'repository'

      - name: Setup Go ("${{ inputs.go-version }}")
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run Go File ("${{ inputs.go-file-path }}")
        run: |
          cd repository  # Necessary so that the go.mod file can be found.
          go run ${{ inputs.go-file-path }}
          ls
          cd code
          ls
          cd sync-workflows
          ls
      
      - name: Check For Job Summary
        run: |
          if test -f summary.md; then
            echo "Job summary file found! Sending to `$GITHUB_STEP_SUMMARY`..."
            echo $(cat summary.md) >> $GITHUB_STEP_SUMMARY
          else
            echo "No job summary file found."
          fi