name: Sync Workflows

on:
  push:
    paths:
      - '.github/workflows/synced_**.yaml'
      - '.github/workflows/synced_**.yml'
      - 'repos.json'
  workflow_dispatch:

env:
  BATCH_SIZE: 2

jobs:
  get-repos:
    uses: 'workflow-sync-poc/common/.github/workflows/run-go-file.yaml@main'
    with:
      go-file-path: 'code/batch-repos/main.go'
      go-args: ${{ env.BATCH_SIZE }}

  sync-repos:
    needs: [ get-repos ]
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        repo-batch: ${{ fromJSON(needs.get-repos.outputs.go-output) }}
    uses: 'workflow-sync-poc/common/.github/workflows/run-go-file.yaml@main'
    with:
      go-file-path: 'code/sync-workflow/main.go'
      go-args: ${{ matrix.repo-batch }}
    secrets: inherit