name: Sync Workflows

on:
  push:
    paths:
      - '.github/workflows/synced_**.yaml'
      - '.github/workflows/synced_**.yml'
      - 'repos.json'
  workflow_dispatch:

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.repos }}
    steps:
      - uses: actions/checkout@v4

      - id: matrix
        run: |
          echo "repos=$(jq -c . < repos.json)" >> $GITHUB_OUTPUT
      
      - run: |
          echo "${{ steps.matrix.outputs.repos }}"

  sync-repos:
    needs: [ get-repos ]
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        target: ${{ fromJSON(needs.get-repos.outputs.matrix) }}
    uses: 'workflow-sync-poc/common/.github/workflows/run-go-file.yaml@main'
    with:
      go-file-path: 'code/sync-workflow/main.go'
      go-args: ${{ matrix.target }}
    secrets: inherit